version: '3.8'

services:
  api:
    build: .
    container_name: spicy_api
    ports:
      - "3333:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db 
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=spicy_db
      - DB_PORT=3306

  db:
    image: mysql:8.0
    container_name: spicy_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spicy_db
    ports:
      - "3306:3306" # Mapeia a porta do MySQL para sua máquina, para podermos nos conectar com um cliente de BD.
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: