version: '3.8'

services:
  # Serviço do Backend (API)
  api:
    build: ./spicy_api
    container_name: spicy_api
    ports:
      - "3333:3000"
    volumes:
      - ./spicy_api:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=spicy_db
      - DB_PORT=3306

  # Serviço do Frontend (UI)
  frontend:
    build: ./spicy_ui
    container_name: spicy_ui
    ports:
      - "5173:5173"
    volumes:
      - ./spicy_ui:/usr/src/app
      - /usr/src/app/node_modules

  # Serviço da Banco de Dados
  db:
    image: mysql:8.0
    container_name: spicy_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spicy_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
