version: '3.8'

services:
  # Serviço do Backend (API)
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    container_name: spicy_api
    ports:
      - "3333:3000"
    volumes:
      - ./packages/api:/usr/src/app/packages/api
      - ./packages/common:/usr/src/app/packages/common
    command: sh -c "cd packages/api && npm run db:migrate && npm run db:seed && npm run dev"
    depends_on:
      db:
        condition: service_healthy

  # Serviço do Frontend (UI)
  frontend:
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
    container_name: spicy_ui
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/packages/ui
    command: sh -c "npm install && npm run dev"

  # Serviço da Base de Dados
  db:
    image: postgres:15
    container_name: spicy_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spicy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d spicy_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: