version: '3.8'

services:
  # Serviço do Backend (API)
  api:
    build:
      context: . # O contexto do build é a raiz do projeto
      dockerfile: ./packages/api/Dockerfile
    container_name: spicy_api
    ports:
      - "3333:3000"
    # ATUALIZAÇÃO AQUI: Montamos a pasta raiz inteira
    volumes:
      - .:/usr/src/app
    # ATUALIZAÇÃO AQUI: Definimos o diretório de trabalho
    working_dir: /usr/src/app/packages/api
    command: sh -c "npm install && npm run dev"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=spicy_db
      - DB_PORT=3306

  # Serviço do Frontend (UI)
  frontend:
    build:
      context: . # O contexto do build é a raiz do projeto
      dockerfile: ./packages/ui/Dockerfile
    container_name: spicy_ui
    ports:
      - "5173:5173"
    # ATUALIZAÇÃO AQUI: Montamos a pasta raiz inteira
    volumes:
      - .:/usr/src/app
    # ATUALIZAÇÃO AQUI: Definimos o diretório de trabalho
    working_dir: /usr/src/app/packages/ui
    command: sh -c "npm install && npm run dev"

  # Serviço da Base de Dados
  db:
    image: mysql:8.0
    container_name: spicy_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spicy_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
