services:
  - type: web
    name: spicy-api
    runtime: node
    plan: free
    rootDir: ./packages/api
    buildCommand: "npm install && npm run build"
    startCommand: "npm run db:migrate && node dist/api/src/server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spicy-db
          property: connectionString
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://kekas-game-ui.vercel.app

  - type: job
    name: spicy-seeder
    runtime: node
    plan: free
    rootDir: ./packages/api
    buildCommand: "npm install && npm run build"
    startCommand: "npm run db:seed"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spicy-db
          property: connectionString

databases:
  - name: spicy-db
    plan: free
    databaseName: spicy_db
    user: spicy_user